security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto
            migrate_from: ['bcrypt']

    providers:
        app_user_provider:
            id: App\Security\BlindIndexUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|assets)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_home
                check_path: /_internal/security-login-check
                enable_csrf: false

    access_control:
        - { path: ^/chat, roles: ROLE_USER }
        - { path: ^/api/(users|chats|attachments), roles: ROLE_USER }
        - { path: ^/api/auth/logout, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
